baseurl = "http://streeetlamp.github.io/Intro-to-the-Internet-of-Things/"
languageCode = "en-us"
title = "Intro to the Internet of Things"
# Enable comments by entering your Disqus shortname
disqusShortname = "arts-iot"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-72775685-1"
theme = "hugo-hikari-theme"
canonifyurls = true

[permalinks]
  post = "/:year/:month/:day/:slug"
  page = "/:slug"

[params]
  name = "Cody Whitby"
  description = "Intro to the Internet of Things - ARTS 391 - 004 Spring 2016"
  copyright = "&#9996; Spring 2016 &nbsp; &nbsp; &nbsp; &#9998; whitbycw@vcu.edu"

  #Intro to the Internet of Things &#183; ARTS 391 &#183; 004 Spring 2016

  pageNotFoundTitle = "Page not found"
  pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
  # Menu items
  title = "Cody Whitby"
  bio = "whitbycw@vcu.edu"